---
- name: Creates directory
  file: path=/usr/lib/jvm state=directory

- name: unpack java
  unarchive: src=roles/oraclejava8/templates/jdk-12.0.1_linux-x64_bin.tar.gz dest=/usr/lib/jvm owner={{ hadoop_user}} group={{ hadoop_group }}

- lineinfile: dest=/home/hadoop/.bashrc regexp="^export JAVA_HOME" line="export JAVA_HOME=/usr/lib/jvm/jdk-12.0.1"

- apt: update_cache=yes upgrade=yes cache_valid_time=86400

- package:
    name: openjdk-7-jdk
    state: present
