---
- name: Install hbase
  hosts: cluster
  remote_user: vagrant
  sudo: yes
  roles:
    - hbase

- name: Install hbase
  hosts: hadoop-master
  remote_user: vagrant
  sudo: yes
  roles:
    - hbase-master

- name: Install hbase
  hosts: hadoop-data
  remote_user: vagrant
  sudo: yes
  roles:
    - hbase-slave
