- include: interface.yml

- apt: update_cache=yes upgrade=yes cache_valid_time=86400
  when: ansible_distribution == 'Ubuntu'

- package:
    name:
      - ssh
      - openssh-client
      - openssh-server

- name: ssh config vagrant
  copy:
    src: authorized_keys
    dest: /home/hadoop/.ssh/authorized_keys
    owner: hadoop
    mode: 0754
