- include: interface.yml

- apt: update_cache=yes upgrade=yes cache_valid_time=86400
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: change confi authorized_keys
  copy:
    src: authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    mode: 0754
  become: yes

- name: change confi masters
  copy:
    src: masters
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/masters
    owner: vagrant
    mode: 0754
  become: yes

- name: change confi slaves
  copy:
    src: slaves
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/slaves
    owner: vagrant
    mode: 0754
  become: yes

- name: remove tmp files
  shell: rm -Rf /app/hadoop/tmp/*
  become: yes
