- include: interface.yml

- apt: update_cache=yes upgrade=yes cache_valid_time=86400
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: ssh key to authorized_keys
  shell : cat /home/hduser/.ssh/id_rsa.pub > /home/hduser/.ssh/authorized_keys

- name: change confi hadoop-env.sh
  copy:
    src: hadoop-env.sh
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hadoop-env.sh
    owner: hduser
    mode: 0754
  become: yes

- name: Creates hadoop tmp directory
  file:
    path: /app/hadoop/tmp
    state: directory
    owner: hduser
    mode: 0754
  become: yes

- name: change confi core-site.xml
  copy:
    src: core-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/core-site.xml
    owner: hduser
    mode: 0754
  become: yes

- name: change confi mapred-site.xml
  copy:
    src: mapred-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/mapred-site.xml
    owner: hduser
    mode: 0754
  become: yes

- name: change confi hdfs-site.xml
  copy:
    src: hdfs-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hdfs-site.xml
    owner: hduser
    mode: 0754

- name: change confi hadoop-env.sh
  copy:
    src: hadoop-env.sh
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hadoop-env.sh
    owner: hduser
    mode: 0754
  become: yes

- name: change confi slaves
  copy:
    src: slaves
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/slaves
    owner: hduser
    mode: 0754
  become: yes
