- include: interface.yml

- apt: update_cache=yes upgrade=yes cache_valid_time=86400
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: change confi authorized_keys
  copy:
    src: authorized_keys
    dest: /home/hduser/.ssh/authorized_keys
    owner: hduser
    mode: 0754
  become: yes

- name: change confi hadoop-env.sh
  copy:
    src: hadoop-env.sh
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hadoop-env.sh
    owner: hduser
    mode: 0754
  become: yes

- name: Creates hadoop tmp directory
  file:
    path: /app/hadoop/tmp
    state: directory
    owner: hduser
    mode: 0754
  become: yes

- name: change confi core-site.xml
  copy:
    src: core-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/core-site.xml
    owner: hduser
    mode: 0754
  become: yes

- name: change confi mapred-site.xml
  copy:
    src: mapred-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/mapred-site.xml
    owner: hduser
    mode: 0754
  become: yes

- name: change confi hdfs-site.xml
  copy:
    src: hdfs-site.xml
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hdfs-site.xml
    owner: hduser
    mode: 0754
  become: yes

- name: change confi hadoop-env.sh
  copy:
    src: hadoop-env.sh
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/hadoop-env.sh
    owner: hduser
    mode: 0754
  become: yes

- name: change confi master
  copy:
    src: masters
    dest: /usr/local/hadoop-3.2.0/etc/hadoop/masters
    owner: hduser
    mode: 0754
  become: yes

- name: don't know why but I cannot execute folder without being root so
  shell: chmod -R 777 /usr/lib/jvm
  become: yes

- name: this is ugly but it works, now I have all rigths
  shell: chmod -R 777 /usr/local/hadoop-3.2.0
  become: yes

- name: remove tmp files
  shell: rm -Rf /app/hadoop/tmp/*
  become: yes

- name: formatting the HDFS
  shell: /usr/local/hadoop-3.2.0/bin/hadoop namenode -format
  become: yes
  ignore_errors: true

- name: import environement
  shell: "{{ item }}"
  with_items:
    - export HADOOP_HOME=/usr/local/hadoop-3.2.0
    - export HADOOP_INSTALL=$HADOOP_HOME
    - export HADOOP_MAPRED_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_HOME=$HADOOP_HOME
    - export HADOOP_HDFS_HOME=$HADOOP_HOME
    - export YARN_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
    - export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bi

- name: starting cluster hadoop
  shell: /usr/local/hadoop-3.2.0/sbin/start-all.sh
